services:
  mcp:
    build: .
    stdin_open: true
    tty: false
    environment:
      ADO_ORG: ${ADO_ORG}
      ADO_MCP_AUTH_TOKEN: ${ADO_MCP_AUTH_TOKEN}
      ADO_DOMAINS: ${ADO_DOMAINS:-core,work,work-items,repositories,wiki}
      ado_mcp_project: ${ado_mcp_project:-}
      ado_mcp_team: ${ado_mcp_team:-}
